local tbl = {
    ["sparkWidth"] = 10,
    ["modelIsUnit"] = false,
    ["iconSource"] = -1,
    ["api"] = false,
    ["xOffset"] = 0,
    ["adjustedMax"] = "1",
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["sparkRotation"] = 0,
    ["sameTexture"] = true,
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["icon"] = false,
    ["slant"] = 0,
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["keepAspectRatio"] = false,
    ["selfPoint"] = "CENTER",
    ["barColor"] = {
        [1] = 0.63921570777893,
        [2] = 0.18823531270027,
        [3] = 0.78823536634445,
        [4] = 1,
    },
    ["desaturate"] = false,
    ["rotation"] = 0,
    ["font"] = "Friz Quadrata TT",
    ["sparkOffsetY"] = 0,
    ["load"] = {
        ["use_petbattle"] = false,
        ["use_never"] = false,
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["class"] = {
            ["multi"] = {
            },
        },
        ["use_vehicleUi"] = false,
        ["use_class_and_spec"] = true,
        ["class_and_spec"] = {
            ["single"] = 581,
        },
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["textureWrapMode"] = "CLAMP",
    ["sequence"] = 1,
    ["startAngle"] = 0,
    ["scale"] = 1,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = true,
    ["regionType"] = "progresstexture",
    ["user_y"] = 0,
    ["model_st_us"] = 40,
    ["information"] = {
        ["debugLog"] = false,
    },
    ["conditions"] = {
        [1] = {
            ["check"] = {
                ["trigger"] = -1,
                ["op"] = "",
                ["variable"] = "customcheck",
                ["value"] = "function(states)\\n    -- ignore stacks below 3\\n    if aura_env.currentStacks < 3 then\\n        return false\\n    end\\n    \\n    -- if Spirit Bomb isn't known, only change color on 5 stacks\\n    if not aura_env.usesSpiritBomb then        \\n        return aura_env.currentStacks >= 5\\n    end\\n    \\n    -- in meta\\n    if states[2] and states[2].show ~= nil and states[2].show then\\n        return aura_env.currentStacks >= 3 \\n    end\\n    \\n    return aura_env.currentStacks >= 4\\nend",
            },
            ["changes"] = {
                [1] = {
                    ["value"] = {
                        [1] = 0.76862752437592,
                        [2] = 0.12156863510609,
                        [3] = 0.23137256503105,
                        [4] = 1,
                    },
                    ["property"] = "foregroundColor",
                },
            },
        },
    },
    ["slantFirst"] = false,
    ["preferToUpdate"] = false,
    ["texture"] = "Details Flat",
    ["foregroundColor"] = {
        [1] = 0.63921570777893,
        [2] = 0.18823531270027,
        [3] = 0.78823536634445,
        [4] = 1,
    },
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["spark"] = false,
    ["tocversion"] = 100007,
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
            ["custom"] = "--- @return number\\naura_env.getStacks = function()\\n    return select(3, WA_GetUnitBuff(\\\"player\\\", 203981)) or 0\\nend\\n\\naura_env.talentedSpiritBomb = function()\\n    local activeConfigId = C_ClassTalents.GetActiveConfigID()\\n    \\n    if not activeConfigId then\\n        aura_env.usesSpiritBomb = false\\n        return\\n    end\\n    \\n    local spiritBombNodeId = 90978\\n    local nodeInfo = C_Traits.GetNodeInfo(activeConfigId, spiritBombNodeId)\\n    aura_env.usesSpiritBomb = nodeInfo.ranksPurchased > 0\\nend\\n\\naura_env.usesSpiritBomb = false\\naura_env.talentedSpiritBomb()\\n\\naura_env.lastStacks = aura_env.getStacks()\\naura_env.currentStacks = aura_env.lastStacks\\n\\nlocal isInMeta = WA_GetUnitBuff(\\\"player\\\", 187827) ~= nil\\n\\n-- full update may be required to make conditional colors happen\\n-- otherwise, only the changed fragments will have their colro adjusted which is giga wonky visually\\n--- @param event \\\"UNIT_AURA\\\" | \\\"TRIGGER\\\" | \\\"OPTIONS\\\" | \\\"STATUS\\\"\\n--- @param updatedTriggerNumber number | string | nil\\n--- @param updatedTriggerStates table | nil\\n--- @return boolean, boolean\\naura_env.shouldPerformFullUpdate = function(event, updatedTriggerNumber, updatedTriggerStates)\\n    if event == \\\"UNIT_AURA\\\" then\\n        if aura_env.currentStacks == aura_env.lastStacks then\\n            return false, true\\n        end\\n        \\n        if aura_env.usesSpiritBomb then\\n            if isInMeta then\\n                -- from sub 3 to 3+\\n                if aura_env.currentStacks >= 3 then\\n                    return aura_env.lastStacks < 3, false\\n                end\\n                \\n                return false, false\\n            end\\n            \\n            -- from sub 4 to 4+\\n            if aura_env.currentStacks >= 4 then\\n                return aura_env.lastStacks < 4, false\\n            end\\n            \\n            return false, false\\n        end\\n        \\n        return false, false\\n    end\\n    \\n    -- only triggers when you ENTER or LEAVE meta\\n    if event == \\\"TRIGGER\\\" and updatedTriggerNumber == 2 then\\n        -- for some reason this table is empty when leaving meta\\n        for _, trigger in pairs(updatedTriggerStates) do\\n            if trigger.triggernum == 2 then\\n                isInMeta = trigger.show\\n                \\n                if aura_env.usesSpiritBomb then\\n                    return aura_env.currentStacks >= 3, false\\n                end\\n                \\n                -- technically redundant, but without returning while seeing meta\\n                -- the dropping out of meta check below would get triggered on entering meta\\n                return aura_env.currentStacks == 5, false\\n            end\\n        end\\n        \\n        if isInMeta then\\n            isInMeta = false\\n            if aura_env.usesSpiritBomb then\\n                return aura_env.currentStacks >= 3, false\\n            end\\n            \\n            return false, false\\n        end\\n    end\\n    \\n    -- STATUS event\\n    return false, false\\nend",
            ["do_custom"] = true,
        },
        ["finish"] = {
        },
    },
    ["model_path"] = "spells/cfx_demonhunter_shatteredsouls_missile.m2",
    ["model_st_rx"] = 270,
    ["auraRotation"] = 0,
    ["anchorFrameType"] = "SCREEN",
    ["config"] = {
    },
    ["useCooldownModRate"] = false,
    ["foregroundTexture"] = "Interface\\\\AddOns\\\\WeakAuras\\\\Media\\\\Textures\\\\Square_White",
    ["sparkHidden"] = "NEVER",
    ["model_z"] = 0,
    ["model_st_tz"] = 0,
    ["backgroundOffset"] = 0,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["backgroundColor"] = {
        [1] = 0.1803921610117,
        [2] = 0.070588238537312,
        [3] = 0.19215688109398,
        [4] = 0.75,
    },
    ["sparkOffsetX"] = 0,
    ["wagoID"] = "ZuEUctQd3",
    ["parent"] = "XephUI-SoulFragments",
    ["alpha"] = 1,
    ["adjustedMin"] = "0",
    ["borderInset"] = 11,
    ["crop_y"] = 0.25,
    ["desaturateBackground"] = false,
    ["cooldownSwipe"] = false,
    ["authorOptions"] = {
    },
    ["sparkRotationMode"] = "AUTO",
    ["cooldownEdge"] = false,
    ["desaturateForeground"] = false,
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["type"] = "custom",
                ["custom_type"] = "stateupdate",
                ["custom_hide"] = "timed",
                ["names"] = {
                },
                ["event"] = "Chat Message",
                ["unit"] = "player",
                ["customDuration"] = "\\n\\n",
                ["subeventPrefix"] = "SPELL",
                ["spellIds"] = {
                },
                ["events"] = "UNIT_AURA:player,TRIGGER:2",
                ["check"] = "event",
                ["custom"] = "-- UNIT_AURA:player,TRIGGER:2\\n--- @class SoulFragmentCloneState\\n--- @field show boolean\\n--- @field total 5\\n--- @field value number\\n--- @field index number\\n--- @field progressType \\\"static\\\"\\n--- @field changed boolean\\n\\n--- @param allstates table<number, SoulFragmentCloneState>\\n--- @param event \\\"UNIT_AURA\\\" | \\\"TRIGGER\\\" | \\\"OPTIONS\\\" | \\\"STATUS\\\"\\n--- @param updatedTriggerNumber nil | number | string\\n--- @param updatedTriggerStates table\\n--- @return boolean\\nfunction (allstates, event, updatedTriggerNumber, updatedTriggerStates)\\n    local stacks = aura_env.getStacks()\\n    aura_env.currentStacks = stacks\\n    \\n    local shouldPerformFullUpdate, canBail =\\n    aura_env.shouldPerformFullUpdate(event, updatedTriggerNumber, updatedTriggerStates)\\n    \\n    if canBail then\\n        return false\\n    end\\n    \\n    local hasChanges = shouldPerformFullUpdate\\n    \\n    for i = 1, 5, 1 do\\n        local value = stacks >= i and 1 or 0\\n        \\n        if allstates[i] then\\n            local changed = shouldPerformFullUpdate or allstates[i].value ~= value\\n            hasChanges = true\\n            \\n            if changed then\\n                allstates[i].value = value\\n                allstates[i].changed = true\\n            end\\n        else\\n            allstates[i] = {\\n                show = true,\\n                index = i,\\n                progressType = \\\"static\\\",\\n                value = value,\\n                total = 5,\\n                changed = true\\n            }\\n        end\\n    end\\n    \\n    aura_env.lastStacks = stacks\\n    \\n    return hasChanges or event == \\\"STATUS\\\"\\nend",
                ["subeventSuffix"] = "_CAST_START",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        [2] = {
            ["trigger"] = {
                ["type"] = "aura2",
                ["useExactSpellId"] = true,
                ["auraspellids"] = {
                    [1] = "187827",
                },
                ["unit"] = "player",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        [3] = {
            ["trigger"] = {
                ["type"] = "custom",
                ["custom_type"] = "event",
                ["custom_hide"] = "timed",
                ["use_genericShowOn"] = true,
                ["genericShowOn"] = "showOnCooldown",
                ["use_exact_spellName"] = true,
                ["realSpellName"] = 0,
                ["use_spellName"] = true,
                ["custom"] = "-- PLAYER_SPECIALIZATION_CHANGED:player, TRAIT_CONFIG_UPDATED\\nfunction()\\n    aura_env.talentedSpiritBomb()\\nend",
                ["unit"] = "player",
                ["events"] = "PLAYER_SPECIALIZATION_CHANGED:player, TRAIT_CONFIG_UPDATED",
                ["event"] = "Spell Known",
                ["use_track"] = true,
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        ["disjunctive"] = "any",
        ["activeTriggerMode"] = 1,
    },
    ["endAngle"] = 360,
    ["internalVersion"] = 65,
    ["model_fileId"] = "1343298",
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["model_st_ty"] = 0,
    ["uid"] = "iMAUHqPhbck",
    ["borderOffset"] = 5,
    ["model_st_ry"] = 0,
    ["discrete_rotation"] = 0,
    ["model_st_tx"] = 0,
    ["version"] = 69,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["border_size"] = 1,
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
    },
    ["height"] = 15.872,
    ["rotate"] = true,
    ["fontSize"] = 12,
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = true,
    ["backgroundTexture"] = "Interface\\\\Addons\\\\WeakAuras\\\\PowerAurasMedia\\\\Auras\\\\Aura3",
    ["source"] = "import",
    ["advance"] = false,
    ["mirror"] = false,
    ["zoom"] = 0,
    ["border"] = false,
    ["borderEdge"] = "None",
    ["backdropColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.5,
    },
    ["borderSize"] = 16,
    ["model_x"] = 0,
    ["icon_side"] = "RIGHT",
    ["model_st_rz"] = 0,
    ["cooldownTextDisabled"] = false,
    ["sparkHeight"] = 30,
    ["color"] = {
        [1] = 0.1803921610117,
        [2] = 0.070588238537312,
        [3] = 0.19215688109398,
        [4] = 0.75,
    },
    ["borderBackdrop"] = "Blizzard Tooltip",
    ["user_x"] = 0,
    ["semver"] = "1.7.1",
    ["compress"] = false,
    ["id"] = "XephUI-SoulFragmentClone",
    ["model_y"] = 0,
    ["frameStrata"] = 1,
    ["width"] = 53,
    ["slantMode"] = "INSIDE",
    ["blendMode"] = "BLEND",
    ["inverse"] = false,
    ["borderColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.5,
    },
    ["orientation"] = "HORIZONTAL",
    ["crop_x"] = 0.36,
    ["cooldown"] = false,
    ["slanted"] = false,
}