local tbl = {
    ["overlays"] = {
        [1] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        [2] = {
            [1] = 0.67843137254902,
            [2] = 0.47058823529412,
            [3] = 1,
            [4] = 1,
        },
        [3] = {
            [1] = 0,
            [2] = 0.34901960784314,
            [3] = 0.23137254901961,
            [4] = 1,
        },
    },
    ["sparkOffsetX"] = 0,
    ["wagoID"] = "ZuEUctQd3",
    ["authorOptions"] = {
    },
    ["preferToUpdate"] = false,
    ["adjustedMin"] = "0%",
    ["yOffset"] = 2,
    ["anchorPoint"] = "CENTER",
    ["sparkWidth"] = 10,
    ["anchorFrameType"] = "SCREEN",
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["actions"] = {
        ["start"] = {
            ["do_custom"] = false,
        },
        ["init"] = {
            ["do_custom"] = false,
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["use_showAbsorb"] = true,
                ["use_absorbMode"] = true,
                ["use_showCost"] = false,
                ["use_unit"] = true,
                ["use_class"] = false,
                ["powertype"] = 6,
                ["use_showHealAbsorb"] = true,
                ["use_powertype"] = true,
                ["debuffType"] = "HELPFUL",
                ["type"] = "unit",
                ["use_absorbHealMode"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["absorbMode"] = "OVERLAY_FROM_END",
                ["use_showIncomingHeal"] = true,
                ["spellIds"] = {
                },
                ["names"] = {
                },
                ["absorbHealMode"] = "OVERLAY_FROM_END",
                ["subeventPrefix"] = "SPELL",
                ["event"] = "Power",
                ["unit"] = "player",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 65,
    ["iconSource"] = 2,
    ["selfPoint"] = "CENTER",
    ["xOffset"] = 0,
    ["adjustedMax"] = "100%",
    ["barColor"] = {
        [1] = 0.76862752437592,
        [2] = 0.12156863510609,
        [3] = 0.23137256503105,
        [4] = 1,
    },
    ["desaturate"] = true,
    ["backgroundColor"] = {
        [1] = 0.19215688109398,
        [2] = 0.16470588743687,
        [3] = 0.16862745583057,
        [4] = 0.75,
    },
    ["enableGradient"] = false,
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["type"] = "subforeground",
        },
        [3] = {
            ["border_size"] = 1,
            ["border_anchor"] = "bg",
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
        [4] = {
            ["text_text_format_p_time_precision"] = 1,
            ["text_text"] = "%1.power",
            ["text_text_format_1.health_big_number_format"] = "AbbreviateNumbers",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_text_format_1.health_decimal_precision"] = 0,
            ["text_text_format_1.power_round_type"] = "floor",
            ["text_text_format_p_time_legacy_floor"] = false,
            ["text_text_format_1.health_format"] = "Number",
            ["text_text_format_1.percenthealth_format"] = "Number",
            ["rotateText"] = "NONE",
            ["text_text_format_unit_realm_name"] = "never",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_text_format_1.health_abbreviate_max"] = 8,
            ["text_text_format_unit_abbreviate"] = false,
            ["text_shadowYOffset"] = -1,
            ["text_text_format_unit_format"] = "Unit",
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_text_format_1.health_round_type"] = "floor",
            ["text_text_format_t_time_precision"] = 1,
            ["text_text_format_1.percenthealth_decimal_precision"] = 1,
            ["text_fontSize"] = 18,
            ["anchorXOffset"] = 0,
            ["text_text_format_t_time_dynamic_threshold"] = 60,
            ["text_text_format_n_format"] = "none",
            ["text_fixedWidth"] = 64,
            ["text_text_format_p_time_format"] = 0,
            ["text_text_format_1.power_decimal_precision"] = 0,
            ["text_text_format_1.health_color"] = true,
            ["text_text_format_p_time_mod_rate"] = true,
            ["text_text_format_1.power_format"] = "Number",
            ["text_selfPoint"] = "CENTER",
            ["text_automaticWidth"] = "Auto",
            ["text_text_format_t_time_legacy_floor"] = false,
            ["text_text_format_t_time_format"] = 0,
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["text_text_format_1.health_realm_name"] = "never",
            ["text_text_format_t_format"] = "timed",
            ["text_text_format_p_time_dynamic_threshold"] = 60,
            ["text_text_format_1.absorb_format"] = "none",
            ["type"] = "subtext",
            ["text_anchorXOffset"] = 0,
            ["text_text_format_p_format"] = "BigNumber",
            ["text_font"] = "Oswald",
            ["text_fontType"] = "None",
            ["text_anchorYOffset"] = -1.75,
            ["text_shadowXOffset"] = 1,
            ["text_text_format_p_big_number_format"] = "AbbreviateLargeNumbers",
            ["text_text_format_t_time_mod_rate"] = true,
            ["text_anchorPoint"] = "INNER_CENTER",
            ["text_text_format_unit_color"] = true,
            ["text_text_format_1.percentHealth_format"] = "none",
            ["text_text_format_1.health_abbreviate"] = false,
            ["text_text_format_c_format"] = "none",
            ["text_text_format_unit_abbreviate_max"] = 8,
        },
    },
    ["gradientOrientation"] = "HORIZONTAL",
    ["parent"] = "XephUI-Bars",
    ["load"] = {
        ["use_petbattle"] = false,
        ["use_never"] = false,
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["class"] = {
            ["single"] = "DEMONHUNTER",
            ["multi"] = {
            },
        },
        ["use_class"] = true,
        ["use_vehicleUi"] = false,
        ["class_and_spec"] = {
            ["multi"] = {
                [250] = true,
            },
        },
        ["use_class_and_spec"] = false,
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "grow",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "spiralandpulse",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["source"] = "import",
    ["frameStrata"] = 4,
    ["information"] = {
        ["forceEvents"] = true,
    },
    ["icon"] = false,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["version"] = 69,
    ["height"] = 16,
    ["icon_side"] = "RIGHT",
    ["id"] = "XephUI-RunicPower",
    ["uid"] = "Chu71A0FCFD",
    ["sparkHeight"] = 30,
    ["texture"] = "Details Flat",
    ["overlaysTexture"] = {
        [1] = "Details Flat",
        [2] = "Details Flat",
        [3] = "Details Flat",
    },
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["semver"] = "1.7.1",
    ["tocversion"] = 100007,
    ["sparkHidden"] = "NEVER",
    ["overlayclip"] = false,
    ["alpha"] = 1,
    ["width"] = 274,
    ["zoom"] = 0.45,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["inverse"] = false,
    ["spark"] = false,
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
    },
    ["barColor2"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 1,
    },
    ["config"] = {
    },
}