local tbl = {
    ["iconSource"] = -1,
    ["wagoID"] = "ZuEUctQd3",
    ["parent"] = "XephUI-VeryImportantDeBuffs",
    ["preferToUpdate"] = false,
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["actions"] = {
        ["start"] = {
            ["sound"] = "Interface\\\\Addons\\\\WeakAuras\\\\PowerAurasMedia\\\\Sounds\\\\shot.ogg",
            ["do_sound"] = false,
        },
        ["init"] = {
            ["do_custom"] = false,
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["showClones"] = false,
                ["type"] = "aura2",
                ["useStacks"] = false,
                ["useExactSpellId"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["event"] = "Health",
                ["names"] = {
                },
                ["spellIds"] = {
                },
                ["auraspellids"] = {
                    [1] = "388801",
                    [2] = "199050",
                    [3] = "388544",
                    [4] = "397904",
                },
                ["unit"] = "player",
                ["subeventPrefix"] = "SPELL",
                ["debuffType"] = "HARMFUL",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["internalVersion"] = 65,
    ["keepAspectRatio"] = true,
    ["selfPoint"] = "CENTER",
    ["desaturate"] = false,
    ["version"] = 69,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["border_size"] = 1,
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
        [3] = {
            ["text_text_format_p_time_precision"] = 1,
            ["text_text_format_s_format"] = "none",
            ["text_text"] = "%p",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_selfPoint"] = "AUTO",
            ["text_automaticWidth"] = "Auto",
            ["text_fixedWidth"] = 64,
            ["text_text_format_p_time_mod_rate"] = true,
            ["text_text_format_c_format"] = "none",
            ["text_justify"] = "CENTER",
            ["rotateText"] = "NONE",
            ["anchorXOffset"] = 0,
            ["text_shadowXOffset"] = 0,
            ["text_text_format_p_time_legacy_floor"] = false,
            ["type"] = "subtext",
            ["text_anchorXOffset"] = 0,
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Oswald",
            ["text_text_format_p_format"] = "timed",
            ["text_anchorYOffset"] = -1.25,
            ["text_fontType"] = "OUTLINE",
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "CENTER",
            ["text_shadowYOffset"] = 0,
            ["text_text_format_p_time_format"] = 0,
            ["text_fontSize"] = 16,
            ["text_text_format_p_time_dynamic_threshold"] = 60,
            ["anchorYOffset"] = 0,
        },
        [4] = {
            ["text_text_format_p_time_precision"] = 1,
            ["text_text_format_s_format"] = "none",
            ["text_text"] = "%s",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_selfPoint"] = "AUTO",
            ["text_automaticWidth"] = "Auto",
            ["text_fixedWidth"] = 64,
            ["text_text_format_p_time_legacy_floor"] = false,
            ["text_justify"] = "CENTER",
            ["rotateText"] = "NONE",
            ["text_shadowXOffset"] = 0,
            ["anchorXOffset"] = 0,
            ["anchorYOffset"] = 0,
            ["type"] = "subtext",
            ["text_anchorXOffset"] = 4,
            ["text_color"] = {
                [1] = 0.76862752437592,
                [2] = 0.12156863510609,
                [3] = 0.23137256503105,
                [4] = 1,
            },
            ["text_font"] = "Oswald",
            ["text_text_format_p_time_mod_rate"] = true,
            ["text_anchorYOffset"] = -4,
            ["text_fontType"] = "OUTLINE",
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "INNER_BOTTOMRIGHT",
            ["text_text_format_p_time_format"] = 0,
            ["text_shadowYOffset"] = 0,
            ["text_fontSize"] = 14,
            ["text_text_format_p_time_dynamic_threshold"] = 60,
            ["text_text_format_p_format"] = "timed",
        },
        [5] = {
            ["glowFrequency"] = 0.25,
            ["type"] = "subglow",
            ["glowXOffset"] = 0,
            ["glowType"] = "ACShine",
            ["glowLength"] = 10,
            ["glowYOffset"] = 0,
            ["glowColor"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["useGlowColor"] = false,
            ["glowScale"] = 1,
            ["glow"] = false,
            ["glowThickness"] = 1,
            ["glowLines"] = 8,
            ["glowBorder"] = false,
        },
    },
    ["height"] = 28,
    ["load"] = {
        ["use_petbattle"] = false,
        ["use_never"] = false,
        ["class"] = {
            ["multi"] = {
            },
        },
        ["race"] = {
            ["single"] = "Troll",
            ["multi"] = {
                ["Troll"] = true,
            },
        },
        ["zoneIds"] = "g433,g2093,g240,g201",
        ["use_zoneIds"] = true,
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_role"] = true,
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class_and_spec"] = {
            ["single"] = 250,
            ["multi"] = {
                [250] = true,
            },
        },
        ["use_spellknown"] = false,
        ["use_vehicle"] = false,
        ["use_vehicleUi"] = false,
        ["size"] = {
            ["multi"] = {
            },
        },
        ["use_exact_spellknown"] = false,
        ["spellknown"] = 391477,
        ["role"] = {
            ["single"] = "TANK",
            ["multi"] = {
                ["TANK"] = true,
            },
        },
    },
    ["source"] = "import",
    ["zoom"] = 0.45,
    ["authorOptions"] = {
    },
    ["regionType"] = "icon",
    ["cooldownEdge"] = false,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["cooldown"] = true,
    ["xOffset"] = 0,
    ["uid"] = "5jGJCOed3Q9",
    ["frameStrata"] = 1,
    ["cooldownTextDisabled"] = true,
    ["semver"] = "1.7.1",
    ["tocversion"] = 100007,
    ["id"] = "XephUI-DFTankDebuffs",
    ["width"] = 32,
    ["alpha"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["useCooldownModRate"] = true,
    ["config"] = {
    },
    ["inverse"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "preset",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "fade",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "pulse",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "preset",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "fade",
            ["duration_type"] = "seconds",
        },
    },
    ["conditions"] = {
        [1] = {
            ["check"] = {
                ["trigger"] = 1,
                ["op"] = "==",
                ["variable"] = "spellId",
                ["value"] = "382628",
            },
            ["changes"] = {
                [1] = {
                    ["value"] = {
                        [1] = 0,
                        [2] = 1,
                        [3] = 0,
                        [4] = 1,
                    },
                    ["property"] = "sub.4.text_color",
                },
            },
        },
    },
    ["information"] = {
        ["forceEvents"] = true,
    },
    ["icon"] = true,
}