local tbl = {
    ["sparkWidth"] = 10,
    ["sparkOffsetX"] = 0,
    ["wagoID"] = "ZuEUctQd3",
    ["parent"] = "XephUI-Bars",
    ["preferToUpdate"] = false,
    ["adjustedMin"] = "0",
    ["yOffset"] = 1,
    ["anchorPoint"] = "CENTER",
    ["zoom"] = 0,
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["icon"] = false,
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["use_rune"] = false,
                ["matchesShowOn"] = "showAlways",
                ["subeventPrefix"] = "SPELL",
                ["check"] = "event",
                ["spellIds"] = {
                },
                ["useExactSpellId"] = true,
                ["use_genericShowOn"] = true,
                ["debuffType"] = "HELPFUL",
                ["use_unit"] = true,
                ["type"] = "unit",
                ["use_absorbHealMode"] = true,
                ["custom_type"] = "status",
                ["names"] = {
                },
                ["fetchTooltip"] = true,
                ["event"] = "Death Knight Rune",
                ["events"] = "",
                ["subeventSuffix"] = "_CAST_START",
                ["rune"] = 0,
                ["auraspellids"] = {
                    [1] = "203981",
                },
                ["use_absorbMode"] = true,
                ["unit"] = "player",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 65,
    ["selfPoint"] = "CENTER",
    ["iconSource"] = -1,
    ["information"] = {
        ["forceEvents"] = true,
    },
    ["barColor"] = {
        [1] = 0.76862752437592,
        [2] = 0.12156863510609,
        [3] = 0.23137256503105,
        [4] = 1,
    },
    ["desaturate"] = false,
    ["authorOptions"] = {
    },
    ["enableGradient"] = false,
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["type"] = "subforeground",
        },
        [3] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "1",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [4] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "2",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [5] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "3.01",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [6] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "4",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [7] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "5",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [8] = {
            ["border_size"] = 1,
            ["border_anchor"] = "bg",
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
    },
    ["gradientOrientation"] = "HORIZONTAL",
    ["backgroundColor"] = {
        [1] = 0.19215688109398,
        [2] = 0.16470588743687,
        [3] = 0.16862745583057,
        [4] = 0.75,
    },
    ["load"] = {
        ["use_petbattle"] = false,
        ["class_and_spec"] = {
            ["single"] = 250,
        },
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["class"] = {
            ["single"] = "DEMONHUNTER",
            ["multi"] = {
            },
        },
        ["use_class"] = true,
        ["use_vehicleUi"] = false,
        ["use_spec"] = true,
        ["spec"] = {
            ["single"] = 2,
            ["multi"] = {
            },
        },
        ["use_class_and_spec"] = true,
        ["use_never"] = false,
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["source"] = "import",
    ["config"] = {
    },
    ["xOffset"] = 0,
    ["width"] = 274,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = true,
    ["regionType"] = "aurabar",
    ["frameStrata"] = 4,
    ["height"] = 16,
    ["icon_side"] = "RIGHT",
    ["sparkHidden"] = "NEVER",
    ["sparkHeight"] = 30,
    ["texture"] = "Details Flat",
    ["spark"] = false,
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["semver"] = "1.7.1",
    ["tocversion"] = 100007,
    ["id"] = "XephUI-Runes",
    ["actions"] = {
        ["start"] = {
            ["do_custom"] = false,
        },
        ["init"] = {
            ["do_custom"] = false,
        },
        ["finish"] = {
            ["do_custom"] = false,
        },
    },
    ["alpha"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["version"] = 69,
    ["uid"] = "cjpiY4f3koa",
    ["inverse"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
    },
    ["barColor2"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 1,
    },
    ["adjustedMax"] = "5",
}