local tbl = {
    ["sparkWidth"] = 10,
    ["sparkOffsetX"] = 0,
    ["wagoID"] = "ZuEUctQd3",
    ["parent"] = "XephUI-Bars",
    ["preferToUpdate"] = false,
    ["adjustedMin"] = "0",
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["zoom"] = 0,
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["icon"] = false,
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["matchesShowOn"] = "showAlways",
                ["subeventPrefix"] = "SPELL",
                ["debuffType"] = "HELPFUL",
                ["type"] = "custom",
                ["useExactSpellId"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["custom_type"] = "status",
                ["fetchTooltip"] = true,
                ["event"] = "Health",
                ["events"] = "UNIT_AURA:player",
                ["customDuration"] = "function ()\\n    local _, _, count = WA_GetUnitBuff(\\\"player\\\", 195181);\\n    \\n    if count == nil then\\n        return 0, 10, true\\n    end\\n    \\n    return count, 10, true\\nend",
                ["spellIds"] = {
                },
                ["custom"] = "function ()\\n    return true\\nend",
                ["custom_hide"] = "timed",
                ["check"] = "event",
                ["names"] = {
                },
                ["auraspellids"] = {
                    [1] = "203981",
                },
                ["unit"] = "player",
            },
            ["untrigger"] = {
            },
        },
        [2] = {
            ["trigger"] = {
                ["type"] = "aura2",
                ["useExactSpellId"] = true,
                ["auraspellids"] = {
                    [1] = "195181",
                },
                ["unit"] = "player",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        ["disjunctive"] = "custom",
        ["customTriggerLogic"] = "function(t)\\n  return t[1]\\nend",
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 65,
    ["selfPoint"] = "CENTER",
    ["iconSource"] = -1,
    ["information"] = {
        ["forceEvents"] = true,
    },
    ["barColor"] = {
        [1] = 0.76862752437592,
        [2] = 0.12156863510609,
        [3] = 0.23137256503105,
        [4] = 1,
    },
    ["desaturate"] = false,
    ["authorOptions"] = {
    },
    ["enableGradient"] = false,
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["type"] = "subforeground",
        },
        [3] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "1",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [4] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "2",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [5] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "3",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [6] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "4",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [7] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "5.01",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [8] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "6",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [9] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "7",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [10] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "8",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [11] = {
            ["tick_blend_mode"] = "ADD",
            ["tick_rotation"] = 0,
            ["tick_xOffset"] = 0,
            ["tick_desaturate"] = false,
            ["automatic_length"] = true,
            ["tick_thickness"] = 1,
            ["tick_placement_mode"] = "AtValue",
            ["use_texture"] = false,
            ["tick_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["tick_texture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
            ["tick_yOffset"] = 0,
            ["tick_visible"] = true,
            ["tick_placement"] = "9",
            ["tick_length"] = 30,
            ["tick_mirror"] = false,
            ["type"] = "subtick",
        },
        [12] = {
            ["border_size"] = 1,
            ["border_anchor"] = "bg",
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
    },
    ["gradientOrientation"] = "HORIZONTAL",
    ["backgroundColor"] = {
        [1] = 0.19215688109398,
        [2] = 0.16470588743687,
        [3] = 0.16862745583057,
        [4] = 0.5,
    },
    ["load"] = {
        ["use_petbattle"] = false,
        ["class_and_spec"] = {
            ["single"] = 250,
        },
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["class"] = {
            ["single"] = "DEMONHUNTER",
            ["multi"] = {
            },
        },
        ["use_class"] = true,
        ["use_vehicleUi"] = false,
        ["use_spec"] = true,
        ["spec"] = {
            ["single"] = 2,
            ["multi"] = {
            },
        },
        ["use_class_and_spec"] = true,
        ["use_never"] = false,
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = true,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["source"] = "import",
    ["config"] = {
    },
    ["xOffset"] = 0,
    ["width"] = 274,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = true,
    ["regionType"] = "aurabar",
    ["frameStrata"] = 4,
    ["height"] = 8,
    ["icon_side"] = "RIGHT",
    ["sparkHidden"] = "NEVER",
    ["sparkHeight"] = 30,
    ["texture"] = "Details Flat",
    ["spark"] = false,
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["semver"] = "1.7.1",
    ["tocversion"] = 100007,
    ["id"] = "XephUI-BoneShield",
    ["actions"] = {
        ["start"] = {
            ["do_custom"] = false,
        },
        ["init"] = {
            ["do_custom"] = false,
        },
        ["finish"] = {
            ["do_custom"] = false,
        },
    },
    ["alpha"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["version"] = 69,
    ["uid"] = "e69vWtbH0Bg",
    ["inverse"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
        [1] = {
            ["check"] = {
                ["trigger"] = -2,
                ["variable"] = "OR",
                ["checks"] = {
                    [1] = {
                        ["trigger"] = 1,
                        ["op"] = "<=",
                        ["variable"] = "expirationTime",
                        ["value"] = "5",
                    },
                    [2] = {
                        ["trigger"] = 2,
                        ["op"] = "==",
                        ["variable"] = "stacks",
                        ["value"] = "1",
                    },
                },
            },
            ["changes"] = {
                [1] = {
                    ["value"] = {
                        ["sound_type"] = "Play",
                        ["sound"] = "Interface\\\\AddOns\\\\WeakAuras\\\\Media\\\\Sounds\\\\RoosterChickenCalls.ogg",
                        ["sound_channel"] = "Master",
                    },
                    ["property"] = "sound",
                },
            },
        },
    },
    ["barColor2"] = {
        [1] = 1,
        [2] = 1,
        [3] = 0,
        [4] = 1,
    },
    ["adjustedMax"] = "10",
}