local tbl = {
    ["overlays"] = {
        [1] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        [2] = {
            [1] = 0.67843137254902,
            [2] = 0.47058823529412,
            [3] = 1,
            [4] = 1,
        },
        [3] = {
            [1] = 0,
            [2] = 0.34901960784314,
            [3] = 0.23137254901961,
            [4] = 1,
        },
    },
    ["sparkOffsetX"] = 0,
    ["wagoID"] = "ZuEUctQd3",
    ["authorOptions"] = {
    },
    ["preferToUpdate"] = false,
    ["adjustedMin"] = "0%",
    ["yOffset"] = 1,
    ["anchorPoint"] = "CENTER",
    ["sparkWidth"] = 10,
    ["anchorFrameType"] = "SCREEN",
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["url"] = "https://wago.io/ZuEUctQd3/69",
    ["actions"] = {
        ["start"] = {
            ["do_custom"] = false,
        },
        ["init"] = {
            ["custom"] = "aura_env.hasFelblade = false\\naura_env.hasSigilOfFlames = false\\naura_env.hasDemonBlades = false\\naura_env.hasInsatiableHunger = false\\naura_env.unrestrainedFuryRanks = 0\\n\\naura_env.updateTalents = function()    \\n    local activeConfigId = C_ClassTalents.GetActiveConfigID()\\n    \\n    if not activeConfigId then\\n        aura_env.hasFelblade = false\\n        aura_env.hasSigilOfFlames = false\\n        aura_env.hasDemonBlades = false\\n        aura_env.hasInsatiableHunger = false\\n        aura_env.unrestrainedFuryRanks = 0\\n        return\\n    end\\n    \\n    local felbladeAuraOfPainChoiceNode = C_Traits.GetNodeInfo(activeConfigId, 90932)\\n    aura_env.hasFelblade = felbladeAuraOfPainChoiceNode.ranksPurchased > 0 and felbladeAuraOfPainChoiceNode.entryIDsWithCommittedRanks[1] == 112842\\n    \\n    local sigilOfFlamesNode = C_Traits.GetNodeInfo(activeConfigId, 90943)\\n    aura_env.hasSigilOfFlames = sigilOfFlamesNode.ranksPurchased > 0\\n    \\n    local insatiableHungerDemonBladesChoiceNode = C_Traits.GetNodeInfo(activeConfigId, 91019)\\n    \\n    if insatiableHungerDemonBladesChoiceNode.ranksPurchased > 0  then\\n        aura_env.hasDemonBlades = insatiableHungerDemonBladesChoiceNode.entryIDsWithCommittedRanks[1] == 112940\\n        aura_env.hasInsatiableHunger = insatiableHungerDemonBladesChoiceNode.entryIDsWithCommittedRanks[1] == 112941\\n    else \\n        aura_env.hasDemonBlades = false\\n        aura_env.hasInsatiableHunger = false\\n    end\\n    \\n    local unrestrainedFuryNode = C_Traits.GetNodeInfo(activeConfigId, 90941)\\n    aura_env.unrestrainedFuryRanks = unrestrainedFuryNode.ranksPurchased\\nend",
            ["do_custom"] = true,
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["use_showAbsorb"] = true,
                ["class"] = "DEMONHUNTER",
                ["use_showCost"] = false,
                ["use_unit"] = true,
                ["use_class"] = true,
                ["powertype"] = 17,
                ["use_absorbMode"] = true,
                ["use_showHealAbsorb"] = true,
                ["use_powertype"] = true,
                ["debuffType"] = "HELPFUL",
                ["names"] = {
                },
                ["type"] = "unit",
                ["use_absorbHealMode"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["absorbMode"] = "OVERLAY_FROM_END",
                ["use_showIncomingHeal"] = true,
                ["spellIds"] = {
                },
                ["absorbHealMode"] = "OVERLAY_FROM_END",
                ["event"] = "Power",
                ["subeventPrefix"] = "SPELL",
                ["use_requirePowerType"] = true,
                ["unit"] = "player",
            },
            ["untrigger"] = {
            },
        },
        [2] = {
            ["trigger"] = {
                ["type"] = "custom",
                ["custom"] = "function()\\n    aura_env.updateTalents()\\nend",
                ["custom_type"] = "event",
                ["custom_hide"] = "timed",
                ["unit"] = "player",
                ["events"] = "PLAYER_SPECIALIZATION_CHANGED:player, TRAIT_CONFIG_UPDATED",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        ["disjunctive"] = "any",
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 65,
    ["iconSource"] = 2,
    ["selfPoint"] = "CENTER",
    ["xOffset"] = 0,
    ["adjustedMax"] = "100%",
    ["barColor"] = {
        [1] = 0.78823536634445,
        [2] = 0.258823543787,
        [3] = 0.99215692281723,
        [4] = 1,
    },
    ["desaturate"] = true,
    ["backgroundColor"] = {
        [1] = 0.1803921610117,
        [2] = 0.070588238537312,
        [3] = 0.19215688109398,
        [4] = 0.75,
    },
    ["enableGradient"] = false,
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["type"] = "subbackground",
        },
        [2] = {
            ["type"] = "subforeground",
        },
        [3] = {
            ["border_size"] = 1,
            ["border_anchor"] = "bg",
            ["border_offset"] = 0,
            ["border_color"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["border_visible"] = true,
            ["border_edge"] = "1 Pixel",
            ["type"] = "subborder",
        },
        [4] = {
            ["text_text_format_p_time_precision"] = 1,
            ["text_text"] = "%1.power",
            ["text_text_format_1.health_big_number_format"] = "AbbreviateNumbers",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_text_format_1.health_decimal_precision"] = 0,
            ["text_text_format_1.power_round_type"] = "floor",
            ["text_text_format_p_time_legacy_floor"] = false,
            ["text_text_format_1.health_format"] = "Number",
            ["text_text_format_1.percenthealth_format"] = "Number",
            ["rotateText"] = "NONE",
            ["text_text_format_unit_realm_name"] = "never",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_text_format_1.health_abbreviate_max"] = 8,
            ["text_text_format_unit_abbreviate"] = false,
            ["text_shadowYOffset"] = -1,
            ["text_text_format_unit_format"] = "Unit",
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_text_format_1.health_round_type"] = "floor",
            ["text_text_format_t_time_precision"] = 1,
            ["text_text_format_1.percenthealth_decimal_precision"] = 1,
            ["text_fontSize"] = 18,
            ["anchorXOffset"] = 0,
            ["text_text_format_t_time_dynamic_threshold"] = 60,
            ["text_text_format_n_format"] = "none",
            ["text_fixedWidth"] = 64,
            ["text_text_format_p_time_format"] = 0,
            ["text_text_format_1.power_decimal_precision"] = 0,
            ["text_text_format_1.health_color"] = true,
            ["text_text_format_p_time_mod_rate"] = true,
            ["text_text_format_1.power_format"] = "Number",
            ["text_selfPoint"] = "CENTER",
            ["text_automaticWidth"] = "Auto",
            ["text_text_format_t_time_legacy_floor"] = false,
            ["text_text_format_t_time_format"] = 0,
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["text_text_format_1.health_realm_name"] = "never",
            ["text_text_format_t_format"] = "timed",
            ["text_text_format_p_time_dynamic_threshold"] = 60,
            ["text_text_format_1.absorb_format"] = "none",
            ["type"] = "subtext",
            ["text_anchorXOffset"] = 0,
            ["text_text_format_p_format"] = "BigNumber",
            ["text_font"] = "Oswald",
            ["text_fontType"] = "None",
            ["text_anchorYOffset"] = -1.75,
            ["text_shadowXOffset"] = 1,
            ["text_text_format_p_big_number_format"] = "AbbreviateLargeNumbers",
            ["text_text_format_t_time_mod_rate"] = true,
            ["text_anchorPoint"] = "INNER_CENTER",
            ["text_text_format_unit_color"] = true,
            ["text_text_format_1.percentHealth_format"] = "none",
            ["text_text_format_1.health_abbreviate"] = false,
            ["text_text_format_c_format"] = "none",
            ["text_text_format_unit_abbreviate_max"] = 8,
        },
    },
    ["gradientOrientation"] = "HORIZONTAL",
    ["parent"] = "XephUI-Bars",
    ["load"] = {
        ["use_petbattle"] = false,
        ["use_never"] = false,
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["class"] = {
            ["single"] = "DEMONHUNTER",
            ["multi"] = {
            },
        },
        ["use_class"] = true,
        ["use_vehicleUi"] = false,
        ["class_and_spec"] = {
            ["single"] = 577,
            ["multi"] = {
            },
        },
        ["use_class_and_spec"] = true,
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "grow",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeType"] = "none",
            ["easeStrength"] = 3,
            ["preset"] = "spiralandpulse",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["source"] = "import",
    ["frameStrata"] = 4,
    ["information"] = {
        ["forceEvents"] = true,
    },
    ["icon"] = false,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["version"] = 69,
    ["height"] = 16,
    ["icon_side"] = "RIGHT",
    ["id"] = "XephUI-FuryHavoc",
    ["uid"] = "nE8HLcXyfNM",
    ["sparkHeight"] = 30,
    ["texture"] = "Details Flat",
    ["overlaysTexture"] = {
        [1] = "Details Flat",
        [2] = "Details Flat",
        [3] = "Details Flat",
    },
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["semver"] = "1.7.1",
    ["tocversion"] = 100007,
    ["sparkHidden"] = "NEVER",
    ["overlayclip"] = false,
    ["alpha"] = 1,
    ["width"] = 274,
    ["zoom"] = 0.45,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["inverse"] = false,
    ["spark"] = false,
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
        [1] = {
            ["check"] = {
                ["trigger"] = 1,
                ["op"] = "<",
                ["variable"] = "power",
                ["value"] = "25",
            },
            ["changes"] = {
                [1] = {
                    ["value"] = {
                        [1] = 0.78823536634445,
                        [2] = 0.258823543787,
                        [3] = 0.99215692281723,
                        [4] = 0.40000003576279,
                    },
                    ["property"] = "barColor",
                },
            },
        },
        [2] = {
            ["check"] = {
                ["trigger"] = -2,
                ["variable"] = "OR",
                ["checks"] = {
                    [1] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "108",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return aura_env.unrestrainedFuryRanks == 2 and aura_env.hasDemonBlades\\nend",
                            },
                        },
                    },
                    [2] = {
                        ["trigger"] = -2,
                        ["variable"] = "OR",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "98",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return aura_env.unrestrainedFuryRanks == 0 and aura_env.hasDemonBlades\\nend",
                            },
                        },
                    },
                    [3] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "90",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return aura_env.unrestrainedFuryRanks == 2 and aura_env.hasSigilOfFlames\\nend",
                            },
                        },
                    },
                    [4] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "88",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return aura_env.unrestrainedFuryRanks == 0 and aura_env.hasDemonBlades\\nend",
                            },
                        },
                    },
                    [5] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "80",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return (aura_env.unrestrainedFuryRanks == 2 and (aura_env.hasFelblade or aura_env.hasInsatiableHunger))\\n    or (aura_env.unrestrainedFuryRanks == 1 and aura_env.hasSigilOfFlames)\\nend",
                            },
                        },
                    },
                    [6] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "70",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return (aura_env.unrestrainedFuryRanks == 0 and aura_env.hasSigilOfFlames) \\n    or (aura_env.unrestrainedFuryRanks == 1 and (aura_env.hasFelblade or aura_env.hasInsatiableHunger))\\nend",
                            },
                        },
                    },
                    [7] = {
                        ["trigger"] = -2,
                        ["variable"] = "AND",
                        ["checks"] = {
                            [1] = {
                                ["trigger"] = 1,
                                ["op"] = ">=",
                                ["variable"] = "power",
                                ["value"] = "60",
                            },
                            [2] = {
                                ["trigger"] = -1,
                                ["variable"] = "customcheck",
                                ["value"] = "function()\\n    return aura_env.unrestrainedFuryRanks == 0 and (aura_env.hasFelblade or aura_env.hasInsatiableHunger)\\nend",
                            },
                        },
                    },
                },
            },
            ["linked"] = true,
            ["changes"] = {
                [1] = {
                    ["value"] = {
                        [1] = 1,
                        [2] = 0.17647059261799,
                        [3] = 0.34117648005486,
                        [4] = 1,
                    },
                    ["property"] = "barColor",
                },
            },
        },
    },
    ["barColor2"] = {
        [1] = 0.63921570777893,
        [2] = 0.18823531270027,
        [3] = 0.78823536634445,
        [4] = 1,
    },
    ["config"] = {
    },
}